### ISSUE TITLE
Locking problems

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/MoniBase#79]
The CI runs show that we somehow introduced a problem with locking:

tests from ODBConcurrentTest failed:

- ODBConcurrentTest>>#testObjectLockingDifferentDatabases #78 and  #76
- ODBConcurrentTest#testBTreeKeyLockin #76

**Comment by MarcusDenker** [comment]
This is on Linux on the CI. We are working on solving the locking in general by not relying on file locking for sharing inside of one image, the flaky tests could be due to a bug in that new code or just a timing problem due to running virtualized... I think it is a timing problem.

**Comment by sebastianconcept** [comment]
@MarcusDenker if you guys can find a way to solve the need of locking from different hosts without relying on file locking that would be amazing. No idea how can that be done tho.

That feature is needed for multi-images pessimistic locking.

**Comment by MarcusDenker** [comment]
Test now seem to run better on the CI after https://github.com/ApptiveGrid/MoniBase/pull/100
